name: Django CI

env:
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: devops_db

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Flake8
        run: |
          pip install flake8
          flake8

      - name: Run Tests
        run: |
          python manage.py test


      - name: test coverage
        run: |
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run manage.py test

      - name: Generate coverage report
        run: coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./cov.html

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t mazene/devops-backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push mazene/devops-backend:latest
      
      - name: Deploy on kubernetes
        run: |
            kubectl --kubeconfig kubernetes/kubeconfig.yaml apply -f kubernetes/django-deployment.yaml


